-- RIssue - Abstract implementation for getting issues and merge requests from git providers
-- Copyright (C) 2026  flamfrosticboio
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <https://www.gnu.org/licenses/>.

---@class rissue.Config
---@field additional_providers string[] List of lua filenames to import
---@field env_file string The name of the env file
---@field env rissue.config.Env
--- A list of api endpoints to fetch. Uses template strings to substitute various details.
---
--- Supported template strings:
--- - {domain} - domain (e.g. `api.github.com`, `gitlab.com`, `<custom_domain>` from git remote url)
--- - {owner} - owner of the repository
--- - {repo} - repository name
---
--- Example: issues="https://{provider}/search/issues?q=repo:{owner}/{repo}+type:issue+is:open"
---@field endpoints table<rissue.provider, rissue.fetch_type.Map<rissue.url[]>>
---@field endpoint_shortcuts table<rissue.provider, rissue.EndpointShortcut>
--- List of options for a provider. See the provider's documentation for the
--- list of options that is supported.
---@field provider_options table<string, table>

---@class rissue.EndpointShortcut
--- List of patterns that can be used on `string:match()`
---@field patterns string[]
---@field domain   rissue.url

-- todo: add method: get provider endpoints

---@class (partial) rissue.Opts: rissue.Config
---@field env? rissue.opts.Env
