default_install_hook_types:
  - pre-commit
  - commit-msg
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: mixed-line-ending
        stages: [pre-commit]
        args: [--fix=lf]
      - id: check-yaml
        stages: [pre-commit]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: insert-license
        files: \.lua$
        args:
          - --license-filepath
          - LICENSE_HEADER.txt
          - --comment-style=--
        stages: [pre-commit]
        exclude: ^types/
      - id: remove-tabs
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          - --verbose
  - repo: local
    hooks:
      - id: format
        name: Format lua files
        entry: stylua
        language: system
        types: [lua]
        stages: [pre-commit]
        pass_filenames: true
      - id: lint
        name: Lint lua files
        entry: selene --config .selene.toml
        language: system
        types: [lua]
        exclude: ^test/
        pass_filenames: true
        stages: [pre-commit]
      - id: lint-tests
        name: Lint lua test files
        entry: selene --config .selene.tests.toml
        language: system
        types: [lua]
        files: ^test/
        pass_filenames: true
        stages: [pre-commit]
      - id: busted
        name: busted
        entry: busted test/ --defer-print --suppress-pending --lua=lua5.1
        language: system
        types: [lua]
        exclude: ^lua/rissue/types/
        pass_filenames: false
        stages: [pre-commit, pre-push]
