#!/bin/bash

export LUA_PATH="./lua/?.lua;./lua/?/init.lua;./test/?.lua;./test/?/init.lua;$LUA_PATH"

if command -v lua5.1 &> /dev/null; then
    LUA_BIN="lua5.1"
elif command -v lua &> /dev/null; then
    LUA_BIN="lua"
else
    echo "Error: lua is not installed." >&2
    exit 1
fi

"$LUA_BIN" "$@"
