-- RIssue - Plugin for getting issues and merge requests from git providers
-- Copyright (C) 2026  flamfrosticboio
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <https://www.gnu.org/licenses/>.

---@class rissue.Config
---@field additional_providers string[] List of lua filenames to import
---@field env_file string The name of the env file
---@field env rissue.config.Env
---@field endpoint_shortcuts table<rissue.ProviderName, rissue.EndpointShortcut>
--- List of options for a provider. See the provider's documentation for the
--- list of options that is supported.
---@field provider_options table<string, table>

---@class rissue.EndpointShortcut
--- List of patterns that can be used on `string:match()`
---@field patterns string[]
---@field domain   rissue.url
--- Additional info to pass to an endpoint shortcut
---@field additional_info table?

---@class (partial) rissue.Opts: rissue.Config
---@field env? rissue.opts.Env
