name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-slim
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6

      - name: Format check
        uses: JohnnyMorganz/stylua-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "2.5.2"
          args: --config-path ./.stylua.toml --check .

      - name: Lint
        uses: NTBBloodbath/selene-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "0.31.0"
          args: lua/ --config .selene.toml

      - name: Lint Tests
        uses: NTBBloodbath/selene-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "0.31.0"
          args: test/ --config .selene.tests.toml

      - name: Setup Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.1 liblua5.1-0-dev luarocks cmake build-essential curl libuv1-dev
          luarocks install --local luv LIBUV_DIR=/usr

      # - name: Cache Luarocks
      #   uses: actions/cache@v6
      #   with:
      #     path: ~/.luarocks
      #     key: ${{ runner.os }}-luarocks-${{ hashFiles('.rockspec/rissue-dev-1.rockspec') }}

      - name: Run Tests
        run: |
          eval $(luarocks path --local --lua-version=5.1)
          luarocks test --local .rockspec/rissue-dev-1.rockspec

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: ./test/api/package-lock.json

      - name: Install Api Dependencies
        working-directory: ./test/api/
        run: |
          npm ci --omit=dev

      - name: Install Specs
        run: |
          eval $(luarocks path --local --lua-version=5.1)
          ./scripts/setup_test_api.sh

      - name: Run Api Tests Parallel
        shell: bash
        env:
          VERBOSE: true
          TEST_STRICT: true
        run: |
          shopt -s globstar
          eval $(luarocks path --local --lua-version=5.1)
          busted --run=api
